name: Deploy Docker Image to Heroku

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag cicdtest:$(date +%s)

  test:
    name: Test the Application
    runs-on: ubuntu-latest
    env:
      PORT: 8000
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Test with Gradle

        run: gradle clean build

  deploy_to_heroku:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: [ test ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ronnie.hartmann@noser.com
#          email: ${{ secrets.HEROKU_EMAIL }}
#          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_api_key: 4831f4da-075b-4c64-b696-d52b4654413e
          heroku_app_name: ronnier
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web

#  push_to_registry:
#    name: Push Docker image to Docker Hub
#    runs-on: ubuntu-latest
#    needs: [ test ]
#
#    steps:
#      - name: Check out the repo
#        uses: actions/checkout@v2
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#        with:
#          images: leo1305/cicdtest
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
#        with:
#          context: .
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}